### ISSUE TITLE
Error: Cannot find module

### ISSUE THREAD

**Issue by mikkimichaelis** [themetalfleece/nodejs-typescript-template#5]
git clone https://github.com/themetalfleece/nodejs-typescript-template.git
cd nodejs......
npm i
npx tsc
npm run start

Error: Cannot find module '/Users/mikki/Projects/nodejs-typescript-template/dist/app.js'

The compiled js is in a subfolder src

**Comment by themetalfleece** [comment]
Hello, thanks for reporting this :)
I just fixed it in the [latest commit](https://github.com/themetalfleece/nodejs-typescript-template/commit/cdfe5021196d6743e921960f1ef3e7665fc78831).
